version: "3.7"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 67
        published: 67
        protocol: udp
        mode: host
      - target: 80
        published: 8040
        protocol: tcp
        mode: host
      - target: 443
        published: 8443
        protocol: tcp
        mode: host
    environment:
      TZ: 'Europe/ZURICH'
      # WEBPASSWORD: 'set a secure password here or it will be random'
<<<<<<< HEAD
      # FTLCONF_REPLY_ADDR4: '192.168.0.69'
      # currently not used
    # Volumes store your data between container upgrades
=======
      # Volumes store your data between container upgrades
>>>>>>> 28aafdb7899c50c154d9d2d7188483146ed36907
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
<<<<<<< HEAD
    # Change SHM_size RAM for php to use
    shm_size: 128M
#    cap_add:
#      - NET_ADMIN
=======
    #    cap_add:
    #      - NET_ADMIN
>>>>>>> 28aafdb7899c50c154d9d2d7188483146ed36907
    restart: unless-stopped
